# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Kevin Wieman"
  repoUrl: "https://github.com/kwierman/kwierman.github.io"
  description: "The Personal Website of Kevin Wierman"
  author: "Kevin Wierman"
